/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  IsOptional,
  IsNumber,
  ValidateNested,
} from "class-validator";
import { ReviewUpdateManyWithoutHotelsInput } from "./ReviewUpdateManyWithoutHotelsInput";
import { Type } from "class-transformer";
import { RoomUpdateManyWithoutHotelsInput } from "./RoomUpdateManyWithoutHotelsInput";

@InputType()
class HotelUpdateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  address?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  city?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  country?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  description?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  rating?: number | null;

  @ApiProperty({
    required: false,
    type: () => ReviewUpdateManyWithoutHotelsInput,
  })
  @ValidateNested()
  @Type(() => ReviewUpdateManyWithoutHotelsInput)
  @IsOptional()
  @Field(() => ReviewUpdateManyWithoutHotelsInput, {
    nullable: true,
  })
  reviews?: ReviewUpdateManyWithoutHotelsInput;

  @ApiProperty({
    required: false,
    type: () => RoomUpdateManyWithoutHotelsInput,
  })
  @ValidateNested()
  @Type(() => RoomUpdateManyWithoutHotelsInput)
  @IsOptional()
  @Field(() => RoomUpdateManyWithoutHotelsInput, {
    nullable: true,
  })
  rooms?: RoomUpdateManyWithoutHotelsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  zipCode?: string | null;
}

export { HotelUpdateInput as HotelUpdateInput };
