/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  IsOptional,
  IsNumber,
  ValidateNested,
} from "class-validator";
import { ReviewCreateNestedManyWithoutHotelsInput } from "./ReviewCreateNestedManyWithoutHotelsInput";
import { Type } from "class-transformer";
import { RoomCreateNestedManyWithoutHotelsInput } from "./RoomCreateNestedManyWithoutHotelsInput";

@InputType()
class HotelCreateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  address?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  city?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  country?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  description?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  rating?: number | null;

  @ApiProperty({
    required: false,
    type: () => ReviewCreateNestedManyWithoutHotelsInput,
  })
  @ValidateNested()
  @Type(() => ReviewCreateNestedManyWithoutHotelsInput)
  @IsOptional()
  @Field(() => ReviewCreateNestedManyWithoutHotelsInput, {
    nullable: true,
  })
  reviews?: ReviewCreateNestedManyWithoutHotelsInput;

  @ApiProperty({
    required: false,
    type: () => RoomCreateNestedManyWithoutHotelsInput,
  })
  @ValidateNested()
  @Type(() => RoomCreateNestedManyWithoutHotelsInput)
  @IsOptional()
  @Field(() => RoomCreateNestedManyWithoutHotelsInput, {
    nullable: true,
  })
  rooms?: RoomCreateNestedManyWithoutHotelsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  zipCode?: string | null;
}

export { HotelCreateInput as HotelCreateInput };
